Repository iZettle/izettle-toolbox, pull requests merged in 2018-10, with the labels that each got.

#281 Add missing `findsbugs/excludes.xml`
  findbugs/excludes.xml
  izettle-emv/pom.xml
  izettle-emv/src/main/java/com/izettle/tlv/ArrayUtils.java
  izettle-emv/src/main/java/com/izettle/tlv/TLV.java
  izettle-emv/src/main/java/com/izettle/tlv/TLVDecoder.java
  izettle-emv/src/test/java/com/izettle/tlv/ArrayUtilsSpec.java
  izettle-jackson/src/main/java/com/izettle/jackson/module/BigDecimalModule.java
  izettle-jackson/src/main/java/com/izettle/jackson/module/InstantRFC3339Module.java
  izettle-jackson/src/main/java/com/izettle/jackson/module/UUIDModule.java
  izettle-java/src/main/java/com/izettle/java/UUIDFactory.java
  pom.xml
Labels: Lights On

#272 Introduces izettle-kotlin library
  izettle-cart/src/test/java/com/izettle/cart/AlterationTest.java
  izettle-kotlin/pom.xml
  izettle-kotlin/src/main/kotlin/com/izettle/kotlin/Optionals.kt
  izettle-kotlin/src/main/kotlin/com/izettle/kotlin/ValueChecks.kt
  izettle-kotlin/src/test/kotlin/com/izettle/kotlin/OptionalsTest.kt
  izettle-kotlin/src/test/kotlin/com/izettle/kotlin/ValueChecksTest.kt
  pom.xml
Labels: Technical Design

#284 Bump to basepom 1.26
  pom.xml
Labels: Tech Debt
